services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - ${DB_PORT:-27017}:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER:-}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD:-}
    volumes:
      - ./rec_controller//mongo/data:/data/db

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    restart: always
    ports:
      - "1883:1883"
    volumes:
      - ./sim/mosquitto.conf:/mosquitto/config/mosquitto.conf