services:
  mqtt-broker:
    container_name: mqtt-broker
    image: eclipse-mosquitto:latest
    networks:
      - fbbridge
    ports:
      - "1883:1883"
    volumes:
      - ./sim/mosquitto.conf:/mosquitto/config/mosquitto.conf

  batt_alert:
    container_name: batt_alert
    build:
      context: ./batt_alert
      dockerfile: Dockerfile
    networks:
      - fbbridge
      
  mongodb:
    image: mongo:latest
    container_name: mongodb
    networks:
      - fbbridge
    ports:
      - ${DB_PORT:-27017}:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - ./rec_controller/mongo/data:/data/db

  rec_controller:
    container_name: rec_controller
    build:
      context: ./rec_controller
      dockerfile: Dockerfile
    networks:
      - fbbridge

networks:
  fbbridge:
    name: fbbridge
    driver: bridge
