apiVersion: apps/v1
kind: Deployment
metadata:
  name: rec-controller-deployment
  labels:
    app: rec-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rec-controller
  template:
    metadata:
      labels:
        app: rec-controller
    spec:
      restartPolicy: Always
      containers:
      - name: rec-controller
        image: ftvdb/rec_controller:latest
        resources:
            requests:
              memory: "64Mi" 
              cpu: "50m"     
            limits:
              memory: "128Mi" # Maximale 128 MB RAM
              cpu: "100m"     # Maximale 0,1 CPU
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: mongodb-root-username
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: mongodb-root-password
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: mongodb-hostname
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: mongodb-port
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: mongodb-database
        