services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - ${DB_PORT:-27017}:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER:-}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD:-}
    volumes:
      - ./mongo/data:/data/db